---
platform: linux

image_resource:
  type: docker-image
  source: {repository: ubuntu, tag: "16.04"}

inputs:
- name: pyfly

run:
  path: bash
  args:
  - -c
  - |
    ./pyfly/configure_container.sh
    ./pyfly/unit_test.sh
    


