---
resources:
- name: pyfly-repo
  type: git
  source:
    uri: https://github.com/sqqqrly/pyfly.git

- name: my-timer
  type: time
  source:
    interval: 2m

jobs:
- name: hello1
  public: true
  serial: true
  plan:
  - get: pyfly-repo
  - get: my-timer
    trigger: true
  - task: hello1
    file: pyfly-repo/cicd/hello.yml
  - task: hello2
    file: pyfly-repo/cicd/hello.yml


