---
resources:
- name: pyfly
  type: git
  source:
    uri: https://github.com/sqqqrly/pyfly.git

#- name: my-timer
#  type: time
#  source:
#    interval: 2m

jobs:
- name: unit_test_pyfly
  public: true
  serial: true
  plan:
  - get: pyfly
    trigger: true
  # - get: my-timer
  #   trigger: true
  - task: Unittest
    file: pyfly/cicd/unit_test.yml
